spring:
  application:
    name: platform-api-registry

server:
  port: 8082

platform:
  api-registry:
    request-timeout: 2s
    parallelism: 8
    services: []
  tracing:
    otel:
      export:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

