global:
  scrape_interval: 10s

scrape_configs:
  - job_name: platform-sample-app
    metrics_path: /actuator/prometheus
    static_configs:
      # If you run the app on the host, Docker Desktop provides this hostname.
      - targets: ["host.docker.internal:8080"]

  - job_name: platform-observability-hub
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]

